In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (4.9.1)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from beautifulsoup4) (2.0.1)

In [2]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import requests

In [3]:
source = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
soup = bs(source.text, 'lxml')

In [4]:
data_lst = []
columns = []
table = soup.find(class_ = 'wikitable')
for idx, tr_tag in enumerate(table.find_all('tr')):
    part = []
    for td in tr_tag.find_all(['td', 'th']):
        part.append(td.text.strip())
    if not columns: #find header of the table
        columns = part
    else:
        data_lst.append(part)

In [5]:
ca_df_bs4 = pd.DataFrame(data = data_lst, columns = columns)
ca_df_bs4.head(12)

   Postal Code           Borough                                Neighbourhood
0          M1A      Not assigned                                 Not assigned
1          M2A      Not assigned                                 Not assigned
2          M3A        North York                                    Parkwoods
3          M4A        North York                             Victoria Village
4          M5A  Downtown Toronto                    Regent Park, Harbourfront
5          M6A        North York             Lawrence Manor, Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7          M8A      Not assigned                                 Not assigned
8          M9A         Etobicoke      Islington Avenue, Humber Valley Village
9          M1B       Scarborough                               Malvern, Rouge
10         M2B      Not assigned                                 Not assigned
11         M3B        North York                                    Don Mills

<h1 align=left><font size=5>SOLVING PART 2</font></h1>
<font size=3>Use the Notebook to build the code to scrape the following Wikipedia page, 
<b>https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M</b>, in order to obtain the data that is in the table of postal codes and to transform the data into a pandas dataframe like the one shown below</font>:

In [6]:
source = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')
table = pd.read_html(source.text)

In [7]:
ca_df = pd.DataFrame(table[0])
ca_df.head(12)

   Postal Code           Borough                                Neighbourhood
0          M1A      Not assigned                                 Not assigned
1          M2A      Not assigned                                 Not assigned
2          M3A        North York                                    Parkwoods
3          M4A        North York                             Victoria Village
4          M5A  Downtown Toronto                    Regent Park, Harbourfront
5          M6A        North York             Lawrence Manor, Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7          M8A      Not assigned                                 Not assigned
8          M9A         Etobicoke      Islington Avenue, Humber Valley Village
9          M1B       Scarborough                               Malvern, Rouge
10         M2B      Not assigned                                 Not assigned
11         M3B        North York                                    Don Mills

<h1 align=left><font size=5>SOLVING PART 3</font></h1>

<ul>
    <li><font size=4><b>The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood</b></font></li>
</ul>

In [8]:
ren_set = {'Postal Code': 'PostalCode', 'Borough':'Borough', 'Neighbourhood': 'Neighborhood'}
ca_df_temp = ca_df.rename(columns=ren_set)
ca_df_temp.head(12)

   PostalCode           Borough                                 Neighborhood
0         M1A      Not assigned                                 Not assigned
1         M2A      Not assigned                                 Not assigned
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7         M8A      Not assigned                                 Not assigned
8         M9A         Etobicoke      Islington Avenue, Humber Valley Village
9         M1B       Scarborough                               Malvern, Rouge
10        M2B      Not assigned                                 Not assigned
11        M3B        North York                                    Don Mills

<ul>

<ul>
    <li><font size=4><b>Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.</b></font></li>
</ul>

In [10]:
ca_df_temp_1 = ca_df_temp[ca_df_temp['Borough'] != 'Not assigned']
ca_df_temp_1.head(12)

,PostalCode,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."

<ul>

<ul>
    <li><font size=4><b>More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown in row 11 in the above table.</b></font></li>
</ul>

In [11]:
if True not in ca_df.duplicated(['Postal Code']).tolist():
    print('No duplicates in the Postal Code column.')
else: 
    print('You should combine rows with duplicates in the Postal Code column')

No duplicates in the Postal Code column.

<ul>

<ul>
    <li><font size=4><b>If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.</b></font></li>
</ul>

In [13]:
if ca_df_temp[(ca_df_temp['Neighborhood'].isna())&(ca_df_temp['Borough'] != 'Not assigned')].shape[0] == 0:
    print('Table is empty, no conditions for our case.')

Table is empty, no conditions for our case.

<ul>

<ul>
    <li><font size=4><b>Clean your Notebook and add Markdown cells to explain your work and any assumptions you are making.</b></font></li>
    <li><font size=4><b>In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.</b></font></li>
</ul>

In [14]:
ca_df_res = ca_df_temp_1.reset_index(drop=True)
ca_df_res

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [15]:
print('The number of rows in the final dataframe:', ca_df_res.shape[0])

The number of rows in the final dataframe: 103

In [16]:
geo_df = pd.read_csv('http://cocl.us/Geospatial_data')
geo_df.head(12)

   Postal Code   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
5          M1J  43.744734 -79.239476
6          M1K  43.727929 -79.262029
7          M1L  43.711112 -79.284577
8          M1M  43.716316 -79.239476
9          M1N  43.692657 -79.264848
10         M1P  43.757410 -79.273304
11         M1R  43.750072 -79.295849

In [17]:
ren_set = {'Postal Code': 'PostalCode'}
geo_df_temp = geo_df.rename(columns=ren_set)

In [18]:
df_merge = pd.merge(ca_df_res, geo_df_temp)
df_merge.head(12)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724